- name: Update package manager
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Upgrade system
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
- name: Create user
  user:
    name: "{{ user_name }}"
