- name: Update package manager
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Upgrade system
  ansible.builtin.apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
