- name: Update package manager
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Upgrade system
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
- name: Create 'wheel' group
  group:
    name: wheel
- name: Create user
  user:
    name: "{{ user_name }}"
    groups: wheel
- name: Configure sudo
  copy:
    content: "%wheel ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/90-wheel-no-password
    mode: 0440
