- name: Install screen
  ansible.builtin.apt:
    name: screen
- name: Configure screen
  ansible.builtin.copy:
    src: screenrc
    dest: /home/{{ common_admin_user }}/.screenrc
    mode: "0644"
    owner: "{{ common_admin_user }}"
    group: "{{ common_admin_user }}"
