- name: Create 'wheel' group
  ansible.builtin.group:
    name: wheel
- name: Create admin user
  ansible.builtin.user:
    name: "{{ users_admin_user }}"
    groups:
      - wheel
      - docker
    shell: /bin/bash
- name: Configure sudo
  ansible.builtin.copy:
    content: "%wheel ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/90-wheel-no-password
    mode: "0440"
- name: Create TLS group
  ansible.builtin.group:
    name: "{{ users_tls_group.name }}"
    gid: "{{ users_tls_group.id }}"
    system: true
- name: Create Traefik group
  ansible.builtin.group:
    name: "{{ users_traefik_user.name }}"
    gid: "{{ users_traefik_user.id }}"
    system: true
- name: Create Traefik user
  ansible.builtin.user:
    name: "{{ users_traefik_user.name }}"
    uid: "{{ users_traefik_user.id }}"
    group: "{{ users_traefik_user.name }}"
    groups: "{{ users_tls_group.name }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    home: /nonexistent
