- name: Create 'wheel' group
  ansible.builtin.group:
    name: wheel
- name: Create user
  ansible.builtin.user:
    name: "{{ users_user_name }}"
    groups:
      - wheel
      - docker
    shell: /bin/bash
- name: Configure sudo
  ansible.builtin.copy:
    content: "%wheel ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/90-wheel-no-password
    mode: "0440"
