name: Terraform Apply
on:
  push:
    tags: ['**']
jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v2
    - name: Initialize all projects
      env:
        OP_CONNECT_HOST: ${{ vars.OP_CONNECT_HOST }}
        OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      run: make init
    - name: Lint
      run: |
        make versions
        make lint
    - name: Apply
      env:
        OP_CONNECT_HOST: ${{ vars.OP_CONNECT_HOST }}
        OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      run: make
