name: Terraform Plan
on:
  push:
    branches: ['**']
jobs:
  plan:
    name: plan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v2
    - name: Initialize all projects
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      run: make init
    - name: Lint
      run: |
        make versions
        make lint
    - name: Plan
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      run: make plan
