- name: Provision web server
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent
    admin_user: stephdewit
  pre_tasks:
    - name: Load Terraform outputs
      ansible.builtin.include_vars:
        file: /dev/stdin
        name: tf
  roles:
    - role: stephdewit.sshca
      vars:
        sshca_user_ca: "{{ lookup('ansible.builtin.url', 'https://{{ pki_domain_name }}/ssh/ca/user.pub', split_lines=False) }}"
        sshca_host_ca: "{{ lookup('ansible.builtin.url', 'https://{{ pki_domain_name }}/ssh/ca/host.pub', split_lines=False) }}"
        sshca_host_principal: "{{ tf.web_server_hostname }}"
    - role: stephdewit.docker
      vars:
        docker_tcp_port: "{{ lookup('ansible.builtin.pipe', 'op read \"op://IaC/Docker SSL server certificate - Kenny/port\"') }}"
        docker_tcp_ca: "{{ lookup('ansible.builtin.url', 'https://{{ pki_domain_name }}/ssl/ca/certificate.pem', split_lines=False) }}"
        docker_tcp_cert: "{{ lookup('ansible.builtin.pipe', 'op read \"op://IaC/Docker SSL server certificate - Kenny/certificate.pem\"') }}"
        docker_tcp_key: "{{ lookup('ansible.builtin.pipe', 'op read \"op://IaC/Docker SSL server certificate - Kenny/private-key.pem\"') }}"
    - role: users
      vars:
        users_admin_user: "{{ admin_user }}"
    - tls
    - role: screen
      vars:
        screen_admin_user: "{{ admin_user }}"
