- name: Provision web server
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  pre_tasks:
    - name: Load Terraform outputs
      ansible.builtin.include_vars:
        file: /dev/stdin
        name: tf
  roles:
    - upgrade
    - sshca
    - docker
    - users
    - tls
