- name: Provision web server
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent
  pre_tasks:
    - name: Load Terraform outputs
      ansible.builtin.include_vars:
        file: /dev/stdin
        name: tf
  roles:
    - upgrade
    - sshca
    - role: docker
      vars:
        docker_tcp_port: "{{ lookup('ansible.builtin.pipe', 'op read \"op://IaC/Docker SSL server certificate - Kenny/port\"') }}"
        docker_tcp_cert: "{{ lookup('ansible.builtin.pipe', 'op read \"op://IaC/Docker SSL server certificate - Kenny/certificate.pem\"') }}"
        docker_tcp_key: "{{ lookup('ansible.builtin.pipe', 'op read \"op://IaC/Docker SSL server certificate - Kenny/private-key.pem\"') }}"
    - users
    - tls
