http:
  middlewares:
    remove-www:
      redirectRegex:
        regex: "^https://www[.]([^/]+)/(.*)"
        replacement: "https://${1}/${2}"
        permanent: true
    prepend-www:
      redirectRegex:
        regex: "^https://([^/]+)/(.*)"
        replacement: "https://www.${1}/${2}"
        permanent: true
    redirect-to-28s:
      redirectRegex:
        regex: "^https://[^/]+/(.*)"
        replacement: "https://twentyeight.solutions/${1}"
    redirect-to-sdwbe:
      redirectRegex:
        regex: "^https://[^/]+/(.*)"
        replacement: "https://www.stephanedewit.be/${1}"
  routers:
    www-prefix:
      entrypoints: [websecure]
      rule: >-
        Host(`www.tools.28.solutions`) ||
        Host(`www.twentyeight.solutions`) ||
        Host(`www.28.solutions`) ||
        Host(`www.id.stephanedewit.be`)
      middlewares: [remove-www]
      service: noop@internal
    28s-alias:
      entrypoints: [websecure]
      rule: >-
        Host(`twentyeightsolutions.be`) ||
        Host(`www.twentyeightsolutions.be`) ||
        Host(`28solutions.be`) ||
        Host(`www.28solutions.be`)
      middlewares: [redirect-to-28s]
      service: noop@internal
    sdwbe-apex:
      entrypoints: [websecure]
      rule: >-
        Host(`stephanedewit.be`)
      middlewares: [prepend-www]
      service: noop@internal
    sdwbe-alias:
      entrypoints: [websecure]
      rule: >-
        Host(`stephanedew.it`) || Host(`www.stephanedew.it`) ||
        Host(`stephdew.it`) || Host(`www.stephdew.it`) ||
        Host(`phane.be`) || Host(`st.phane.be`) || Host(`ste.phane.be`) ||
        Host(`sdw.ovh`) || Host(`www.sdw.ovh`) ||
        Host(`sdw-home.ovh`) || Host(`www.sdw-home.ovh`)
      middlewares: [redirect-to-sdwbe]
      service: noop@internal
