tls:
  certificates:
%{ for certificate in certificates ~}
    - certFile: /etc/ssl/local-certs/${certificate.common_name}.pem # Expires on ${certificate.not_after}
      keyFile: /etc/ssl/private/${certificate.common_name}.pem
%{ endfor ~}
  options:
    default:
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
