global:
  sendAnonymousUsage: true
log:
  level: DEBUG
accessLog: {}
metrics:
  otlp:
    explicitBoundaries: [0.1, 0.3, 1.2, 5]
    grpc:
      endpoint: ${otel_collector_grpc}
      insecure: true
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: false
tracing:
  sampleRate: 0.1
  otlp:
    grpc:
      endpoint: ${otel_collector_grpc}
      insecure: true
providers:
  file:
    directory: /etc/traefik/dynamic
  docker:
    endpoint: tcp://docker-proxy:2375
    exposedByDefault: false
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}
  api:
    address: ":8080"
api: {}
