global:
  sendAnonymousUsage: true
%{ if enabled_telemetry.logs }
experimental:
  otlpLogs: true
%{ endif }
log:
  level: DEBUG
%{ if enabled_telemetry.logs }
  otlp:
    grpc:
      endpoint: ${otel_collector_grpc}
      insecure: true
%{ endif }
%{ if enabled_telemetry.logs }
accessLog:
  otlp:
    grpc:
      endpoint: ${otel_collector_grpc}
      insecure: true
%{ else }
accessLog: {}
%{ endif }
%{ if enabled_telemetry.metrics }
metrics:
  otlp:
    explicitBoundaries: [0.1, 0.3, 1.2, 5]
    grpc:
      endpoint: ${otel_collector_grpc}
      insecure: true
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: false
%{ endif }
%{ if enabled_telemetry.traces }
tracing:
  sampleRate: 0.1
  otlp:
    grpc:
      endpoint: ${otel_collector_grpc}
      insecure: true
%{ endif }
providers:
  file:
    directory: /etc/traefik/dynamic
  docker:
    endpoint: tcp://${docker_proxy_endpoint}
    exposedByDefault: false
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}
      middlewares:
        - hsts-header@file
  api:
    address: ":8080"
api: {}
