http:
  routers:
    wkd:
      entrypoints: [websecure]
      rule: >-
        Host(`openpgpkey.stephanedewit.be`) ||
        Host(`openpgpkey.twentyeight.solutions`)
      middlewares:
        - add-wkd-prefix
        - add-cors-headers
      service: pki
  middlewares:
    add-wkd-prefix:
      addPrefix:
        prefix: /gpg/wkd
    add-cors-headers:
      headers:
        accessControlAllowMethods: [GET]
        accessControlAllowOriginList: ["*"]
