- name: Download host CA public key
  get_url:
    url: https://www.stephanedewit.be/ssh/host-ca.pub
    dest: /etc/ssh/host-ca.pub
    mode: 0644
- name: List host keys
  find:
    path: /etc/ssh
    patterns: ssh_host_*_key.pub
  register: host_keys
- name: Sign host keys
  community.crypto.openssh_cert:
    type: host
    signing_key: /etc/ssh/host-ca.pub
    use_agent: true
    public_key: "{{ item }}"
    path: "{{ item | replace('.pub', '-cert.pub') }}"
    mode: 0644
    valid_from: always
    valid_to: forever
    identifier: kenny.hosts.28.solutions host key
    principals: [kenny.hosts.28.solutions]
  with_items: "{{ host_keys.files | map(attribute='path') }}"
  notify: reload SSH service
- name: Register host keys certificates
  template:
    src: host-certs.conf.j2
    dest: /etc/ssh/sshd_config.d/host-certs.conf
    mode: 0644
  notify: reload SSH service
