- name: Copy host CA public key
  ansible.builtin.copy:
    content: "{{ sshca_host_ca }}"
    dest: /etc/ssh/host-ca.pub
    mode: "0644"
- name: List host keys
  ansible.builtin.find:
    path: /etc/ssh
    patterns: ssh_host_*_key.pub
  register: host_keys
- name: Sign host keys
  community.crypto.openssh_cert:
    type: host
    signing_key: /etc/ssh/host-ca.pub
    use_agent: true
    public_key: "{{ item }}"
    path: "{{ item | replace('.pub', '-cert.pub') }}"
    mode: "0644"
    valid_from: +0s
    valid_to: +26w
    valid_at: +2w
    ignore_timestamps: true
    identifier: "{{ sshca_host_principal }} host key"
    principals: ["{{ sshca_host_principal }}"]
  with_items: "{{ host_keys.files | map(attribute='path') }}"
  notify: Reload SSH service
- name: Register host keys certificates
  ansible.builtin.template:
    src: host-certs.conf.j2
    dest: /etc/ssh/sshd_config.d/host-certs.conf
    mode: "0644"
  notify: Reload SSH service
