name: Lint
on:
  push:
    branches: ['**']
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Initialize all projects
      run: tf_init_params=-backend=false make init
    - name: Lint
      run: |
        make versions
        make lint
