name: Linting
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
    - name: Initialize Terraform
      run: |
        terraform -chdir=bootstrap init -backend=false
        terraform -chdir=provisioning init -backend=false
        terraform -chdir=services init -backend=false
    - name: Install Python
      uses: actions/setup-python@v5
    - name: Install Ansible Lint
      run: pip install ansible ansible-lint
    - name: Lint
      run: make versions lint
